name: Deploy Backend
on: [push]
jobs:
  using-github-secrets:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Create .env file
              working-directory: ./server
              run: |
                  touch .env
                  echo "${{secrets.BE_ENV}}" >> .env

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install Netlify
        working-directory: ./server
        run: npm install netlify-cli@17.10.1 -g
      - name: Install Dependencies
        working-directory: ./server
        run: npm ci
      - name: Deploy to Netlify
        working-directory: ./server
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
